# STEP 0 -- Index of Small Task Enhancement Proposals (STEPs)
    
## Introduction
    
    This STEP contains the index of all Small Task Enhancement Proposals for this project,
    known as STEPs.  STEP numbers are assigned by the STEP editors, and
    once assigned are never changed.  The Git history of
    the STEP texts represent their historical record.
    
## Informational STEPs
    
    [step-0001](./step-0001.mmd) -- Transform a mind map to a YAML file
    
