# STEP 0001 -- Transform a mind map to a YAML file
    
## Abstract
    
    ~~~
        # Transform a mind map to a YAML file
        lisnp a_mind_map.mm mm2yaml a_mind_map.yaml
        ~~~
        
    

## Informational PEPs
    
    
